name: google_maps_in_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.9.0
  # 次の2行を追加してください
  http: ^0.13.0
  json_serializable: ^6.0.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  pedantic: ^1.4.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
